source 'http://rubygems.org'

gem 'rails', '4.0.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'haml-rails'
gem 'devise'
gem 'cancan'
gem 'paperclip'
gem 'ckeditor'
gem 'gritter', '1.0.3'
gem 'permalink'
gem 'awesome_nested_set'
gem 'russian'
gem 'json'
gem 'rails_admin'
gem 'yaml_db'
gem 'bootstrap-sass'
gem 'compass-rails', github: "Compass/compass-rails", branch: "rails4-hack"
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'

group :development do
  gem 'letter_opener'
  gem 'thin'
  gem 'rails4_upgrade'
end

gem 'unicorn'
gem 'capistrano'
gem 'capistrano-rails', '~> 1.1.0'
gem 'execjs'
gem 'therubyracer'
