# Use the README file as a reference to customize settings.

Article:
  search: title
  filters: help_info
  fields:
    default: title, meta_title, parent, help_info
    form: title, meta_title, body, parent, help_info
    options:
      templates:
        body: text_with_ckeditor
  relationships:
  application: Application
