# Use the README file as a reference to customize settings.

News:
  fields:
    default: title, date, body, portfolio
    form: title, date, body, portfolio
    options:
      templates:
        body: text_with_ckeditor
    search: title
  relationships: 
  application: Application
