# Use the README file as a reference to customize settings.

Portfolio:
  fields:
    default: name, portfolio_image
    form: name, portfolio_image
  relationships: portfolio_items
  application: Application
