# Use the README file as a reference to customize settings.

SpecialOffer:
  fields:
    default: name, special_image_file_name, special_image_file_size, article_id
    form: name, special_image_file_name, special_image_file_size, article_id
  relationships: 
  application: Application
